config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Vonage SMS Delivery Receipt
  resources :sms_delivery_receipts, only: [:create]
  
  resources :campaigns, only: [:index, :new, :create, :show]
  resources :audiences
  get 'users/profile'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: "pages#dashboard", as: :authenticated_root
      get '/users', to: 'devise/registrations#edit'
      get '/profile', to: 'users#profile', as: :profile
      get '/transactions', to: 'pages#transactions', as: :transactions
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
      get '/users', to: 'devise/registrations#new'
    end

    get '/users/password', to: 'devise/passwords#new'
  end

  root :to => "devise/sessions#new"
end

app/models/audience.rb
class Audience < ApplicationRecord
  acts_as_paranoid
  belongs_to :user

  validates_presence_of :name
  validates_presence_of :email, uniqueness: true
  validates_presence_of :contact_number, uniqueness: true
end

app/controllers/audiences_controller.rb
class AudiencesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_audience, only: %i[ show edit update destroy ]

  def index
    if params[:search]
      all_audiences = Audience.all.order(created_at: :desc).where(["name like ?", "%#{params[:search]}%"])
      @audiences = Kaminari.paginate_array(all_audiences).page(params[:page]).per(10)
    else
      all_audiences = Audience.all.order(created_at: :desc)
      @audiences = Kaminari.paginate_array(all_audiences).page(params[:page]).per(10)
    end
  end

  def show
  end

  def new
    @audience = current_user.audiences.build
  end

  def edit
  end

  def create
    @audience = current_user.audiences.build(audience_params)

    respond_to do |format|
      if @audience.save
        format.html { redirect_to audience_url(@audience), notice: "Audience was successfully created." }
        format.json { render :show, status: :created, location: @audience }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @audience.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @audience.update(audience_params)
        format.html { redirect_to audience_url(@audience), notice: "Audience was successfully updated." }
        format.json { render :show, status: :ok, location: @audience }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @audience.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @audience.destroy

    respond_to do |format|
      format.html { redirect_to audiences_url, notice: "Audience was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    def set_audience
      @audience = Audience.find(params[:id])
    end

    def audience_params
      params.require(:audience).permit(:name, :email, :contact_number, :user_id)
    end
end

app/helpers/audiences_helper.rb
module AudiencesHelper
end

app/views/audiences/_form.html.erb
<%= form_with(model: audience, class: "contents") do |form| %>
  <% if audience.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <ul>
        <% audience.errors.each do |error| %>
          <li><i class="fa-sharp fa-regular fa-circle-dot"></i> <%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name, :class=> label_class %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-1 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email, :class=> label_class %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-1 w-full" %>
  </div>

  <div class="my-5">
    <label class="<%= label_class%>">Contact Number</label>
    <%= form.text_field :contact_number, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-1 w-full" %>
  </div>

  <div class="my-5">
    <%= form.hidden_field :user_id %>
  </div>

  <div class="inline">
    <%= button_tag(type: "submit", class: "rounded-lg py-3 px-5 bg-gray-700 text-white inline-block font-medium cursor-pointer") do %>
      <i class="fa-solid fa-circle-check"></i> <%= action_name == "new" ? "Create" : "Update"%> Audience
    <% end %>
  </div>
<% end %>

app/views/audiences/edit.html.erb
<% provide(:title, "Your Audience")%>

<div class="flex container mx-auto px-4 mt-3">
  <div class="w-full">
    <div class="w-full mx-auto my-4 bg-white shadow-xl rounded-xl">
      <div class="p-6">
        <h1 class="font-bold text-2xl text-gray-500">Update Audience</h1>
        <%= render "form", audience: @audience %>
        <%= link_to audiences_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" do %>
          <i class="fa-solid fa-angle-left"></i> Back
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/audiences/index.html.erb
<% provide(:title, "All Audiences")%>

<div class="flex container mx-auto px-4 mt-3">
  <div class="w-full">
    <div class="w-full mx-auto my-4">
      <div class="flex justify-between my-3">
        <div>
          <%= link_to new_audience_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" do %>
            <i class="fa-solid fa-plus"></i> Add Audience
          <% end %>
        </div>
        <div>
        <%= form_tag audiences_path, method: :get do %>
          <%= text_field_tag :search, params[:search], :class=>'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-1 w-full', placeholder: 'Search your audience'%>
        <% end %>
        </div>
      </div>
      <div class="p-0">
        <div class="relative overflow-x-auto">
                <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400" id="audiences_table">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th scope="col" class="px-6 py-3">
                              <i class="fa-solid fa-circle-user mr-1"></i>  Name
                            </th>
                            <th scope="col" class="px-6 py-3">
                              <i class="fa-solid fa-envelope-open mr-1"></i>  Email
                            </th>
                            <th scope="col" class="px-6 py-3">
                              <i class="fa-solid fa-square-phone mr-1"></i>  Contact Number
                            </th>
                            <th scope="col" class="px-6 py-3">
                              <i class="fa-solid fa-calendar-day mr-1"></i>  Date Added
                            </th>
                            <th scope="col" class="px-6 py-3">
                              <i class="fa-solid fa-gear mr-1"></i>  Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                      <% @audiences.each.with_index(1) do |audience| %>
                        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                          <td class="px-6 py-4">
                            <%= audience.name %>
                          </td>
                          <td class="px-6 py-4">
                            <%= audience.email %>
                          </td>
                          <td class="px-6 py-4">
                            <%= audience.contact_number %>
                          </td>
                          <td class="px-6 py-4">
                            <%= audience.created_at.strftime("%B, %d, %Y") %>
                          </td>
                          <td class="px-6 py-4">
                            <%= link_to audience, :class=>"px-4 py-2 bg-green-400 rounded-full text-black" do %>
                              <i class="fa-regular fa-circle-right"></i> View Audience
                            <% end %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                </table>
            </div>
        <%= paginate @audiences, :class=>"bg-gray-700"%>
      </div>
    </div>
  </div>
</div>

app/views/audiences/new.html.erb
<% provide(:title, "New Audience")%>

<div class="flex container mx-auto px-4 mt-3">
  <div class="w-full">
    <div class="w-full mx-auto my-4 bg-white shadow-xl rounded-xl">
      <div class="p-6">
        <h1 class="font-bold text-2xl text-gray-500">Add New audience</h1>
        <%= render "form", audience: @audience %>
        <%= link_to audiences_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" do %>
          <i class="fa-solid fa-angle-left"></i> Back
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/audiences/show.html.erb
<% provide(:title, "Your Audience")%>

<section>
  <div class="relative items-center w-full px-5 py-12 mx-auto md:px-12 lg:px-24 max-w-7xl">
    <div class="grid grid-cols-1">
      <div class="w-full max-w-7xl mx-auto my-4 bg-white shadow-xl rounded-xl">
        <div class="p-6 lg:text-center">
          <span class="mb-8 text-xs font-semibold tracking-widest text-blue-600 uppercase"> Audience Profile</span>
          <h4 class="mt-8 text-2xl font-semibold leading-none tracking-tighter text-neutral-600 lg:text-3xl"><%= @audience.name %></h4>
          <p class="mt-3 text-base leading-relaxed text-gray-500">
            <div>
              <div><i class="fa-solid fa-pizza-slice"></i> Added Since: <%= @audience.created_at.strftime("%B, %d, %Y")%></div>
            </div>
          </p>

          <div class="mt-4">
            <div class="relative overflow-x-auto">
                <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th scope="col" class="px-6 py-3">
                                Name
                            </th>
                            <th scope="col" class="px-6 py-3">
                                Email
                            </th>
                            <th scope="col" class="px-6 py-3">
                                Contact Number
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                          <td class="px-6 py-4">
                            <%= @audience.name %>
                          </td>
                          <td class="px-6 py-4">
                            <%= @audience.email %>
                          </td>
                          <td class="px-6 py-4">
                            <%= @audience.contact_number %>
                          </td>
                        </tr>
                    </tbody>
                </table>
            </div>
          </div>
          <div class="mt-6">
            <%= link_to edit_audience_path(@audience), :class=>"flex items-center justify-center w-full px-10 py-4 text-base font-medium text-center text-white transition duration-500 ease-in-out transform bg-gray-700 rounded-xl hover:bg-gray-800 focus:outline-none" do %>
              <i class="fa-sharp fa-regular fa-pen-to-square mr-2"></i> Update Audience
            <% end %>

            <%= link_to audience_path(@audience), data:{"turbo-method": :delete, "turbo-confirm": "Are you sure"}, :class=>"mt-3 flex items-center justify-center w-full px-10 py-4 text-base font-medium text-center text-white transition duration-500 ease-in-out transform bg-red-400 rounded-xl hover:bg-red-500 focus:outline-none" do %>
              <i class="fa-sharp fa-regular fa-pen-to-square mr-2"></i> Delete Audience
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>