config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Vonage SMS Delivery Receipt
  resources :sms_delivery_receipts, only: [:create]
  
  resources :campaigns, only: [:index, :new, :create, :show]
  resources :audiences
  get 'users/profile'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: "pages#dashboard", as: :authenticated_root
      get '/users', to: 'devise/registrations#edit'
      get '/profile', to: 'users#profile', as: :profile
      get '/transactions', to: 'pages#transactions', as: :transactions
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
      get '/users', to: 'devise/registrations#new'
    end

    get '/users/password', to: 'devise/passwords#new'
  end

  root :to => "devise/sessions#new"
end

app/views/shared/_flashes.html.erb
<% flash.each do |type, message| %>
  <div class="<%= flash_classes(type) %>" id="notice_wrapper">
    <%= message %>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="flex flex-wrap items-center justify-between py-3 text-gray-700 bg-white container mx-auto px-4" data-controller="nav">
  <div class="flex items-center mr-6 flex-no-shrink">
    <%= link_to image_tag("brand.png", :class=>"h-9 w-9"), root_path %>
  </div>
  <div class="block lg:hidden">
    <button class="flex items-center p-2 -mr-1 rounded-lg focus:bg-gray-100" data-action="click->nav#toggleMenu touch->nav#toggleMenu">
      <svg class="stroke-current text-gray-500 w-7 h-7" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><title>Menu</title><g fill="none"><path d="M4 6h16M4 12h8m-8 6h16" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></g></svg>
    </button>
  </div>
  <div class="items-center w-full text-center lg:flex-1 lg:flex lg:text-left pt-2 lg:pt-0 hidden" data-nav-target="menu">
    <div class="lg:flex-grow">
      <%= link_to "CampaignX", root_path, class: "font-semibold p-3 hover:text-gray-700 transition ease duration-300 rounded-lg text-center lg:inline-block block" %>
    </div>
    <div class="font-semibold text-gray-500 text-sm items-center block w-full mt-2 text-center lg:flex lg:flex-row lg:flex-1 lg:mt-0 lg:text-left lg:justify-end">
      <div><%# More links can go here %></div>
      <% if user_signed_in? %>
        <%= link_to profile_path(@user), class: "p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" do %>
          <i class="fa-solid fa-circle-user text-gray-500"></i> <%= current_user.name.full %>
        <% end %>

        <%= link_to transactions_path, :class=>"p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" do %>
          <i class="fa-solid fa-arrow-right-arrow-left"></i> Transaction History
        <% end %>

        <%= button_to destroy_user_session_path, method: :delete, class:"p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" do %>
          <i class="fa-solid fa-arrow-right-from-bracket text-gray-500"></i> Log Out
        <% end %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path, class:"p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %>
        <%= link_to "Sign up", new_user_registration_path, class:"p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block lg:ml-2" %>

        <span class="h-5 w-px bg-gray-200 mx-3"></span>

        <%= link_to "https://github.com/justalever/kickoff_tailwind", target: :_blank, class: "group lg:ml-2 flex justify-center" do %>
          <svg class="fill-current text-gray-400 group-hover:text-gray-600" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_nav_public.html.erb
<nav class="flex flex-wrap items-center justify-between py-3 text-gray-700 bg-white container mx-auto px-4" data-controller="nav">
  <div class="flex items-center mr-6 flex-no-shrink">
    <%= link_to image_tag("brand.png", :class=>"h-9 w-9"), root_path %>
  </div>
  <div class="block lg:hidden">
    <button class="flex items-center p-2 -mr-1 rounded-lg focus:bg-gray-100" data-action="click->nav#toggleMenu touch->nav#toggleMenu">
      <svg class="stroke-current text-gray-500 w-7 h-7" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><title>Menu</title><g fill="none"><path d="M4 6h16M4 12h8m-8 6h16" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></g></svg>
    </button>
  </div>
  <div class="items-center w-full text-center lg:flex-1 lg:flex lg:text-left pt-2 lg:pt-0 hidden" data-nav-target="menu">
    <div class="lg:flex-grow">
      <%= link_to "CampaignX", root_path, class: "font-semibold p-3 hover:text-gray-700 transition ease duration-300 rounded-lg text-center lg:inline-block block" %>
    </div>
    <div class="items-center block w-full mt-2 text-center lg:flex lg:flex-row lg:flex-1 lg:mt-0 lg:text-left lg:justify-end">
      <div><%# More links can go here %></div>
      <% if user_signed_in? %>
        <%= link_to edit_user_registration_path, class: "p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" do %>
          <i class="fa-solid fa-gear text-gray-500"></i> Account Settings
        <% end %>

        <%= button_to destroy_user_session_path, method: :delete, class:"p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" do %>
          <i class="fa-solid fa-arrow-right-from-bracket text-gray-500"></i> Log Out
        <% end %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path, class:"p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %>
        <%= link_to "Sign up", new_user_registration_path, class:"p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block lg:ml-2" %>

        <span class="h-5 w-px bg-gray-200 mx-3"></span>

        <%= link_to "https://github.com/justalever/kickoff_tailwind", target: :_blank, class: "group lg:ml-2 flex justify-center" do %>
          <svg class="fill-current text-gray-400 group-hover:text-gray-600" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>