config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Vonage SMS Delivery Receipt
  resources :sms_delivery_receipts, only: [:create]
  
  resources :campaigns, only: [:index, :new, :create, :show]
  resources :audiences
  get 'users/profile'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: "pages#dashboard", as: :authenticated_root
      get '/users', to: 'devise/registrations#edit'
      get '/profile', to: 'users#profile', as: :profile
      get '/transactions', to: 'pages#transactions', as: :transactions
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
      get '/users', to: 'devise/registrations#new'
    end

    get '/users/password', to: 'devise/passwords#new'
  end

  root :to => "devise/sessions#new"
end

app/views/pages/dashboard.html.erb
<% provide(:title, "Dashboard")%>

<section class="flex container mx-auto px-4 justify-center items-center">
  <div class="w-1/2 mr-2">
    <div class="w-full max-w-4xl mx-auto my-4 bg-white shadow-xl rounded-xl">
      <div class="p-6">
        <span class="mb-8 text-xs font-semibold tracking-widest text-black uppercase"><i class="fa-regular fa-user font-semibold text-black"></i> Audience</span>
        <p class="mt-3 text-base leading-relaxed text-gray-500">Manage your audiences</p>
        <div class="flex gap-2 mt-0 lg:mt-6 max-w-7xl">
          <div class="mt-3 rounded-lg sm:mt-0">
            <%= link_to new_audience_path, :class=>"items-center block px-10 py-3.5 text-base font-medium text-center text-gray-600 transition duration-500 ease-in-out transform border-2 border-white shadow-md rounded-xl focus:outline-none" do %>
              <i class="fa-solid fa-plus"></i> Create Audience
            <% end %>
          </div>
          <div class="mt-3 rounded-lg sm:mt-0 sm:ml-3">
            <%= link_to audiences_path, :class=>"items-center block px-10 py-3.5 text-base font-medium text-center text-gray-200 bg-gray-700 transition duration-500 ease-in-out transform border-2 border-white shadow-md rounded-xl focus:outline-none" do %>
              <i class="fa-solid fa-bars-staggered"></i> Browse Audiences
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="w-1/2 ml-2">
    <div class="w-full max-w-4xl mx-auto my-4 bg-white shadow-xl rounded-xl">
      <div class="p-6">
        <span class="mb-8 text-xs font-semibold tracking-widest text-black uppercase"><i class="fa-solid fa-tower-broadcast"></i> Campaign</span>
        <p class="mt-3 text-base leading-relaxed text-gray-500">Manage your campaigns</p>
        <div class="flex gap-2 mt-0 lg:mt-6 max-w-7xl">
          <div class="mt-3 rounded-lg sm:mt-0">
            <%= link_to new_campaign_path, :class=>"items-center block px-10 py-3.5 text-base font-medium text-center text-gray-600 transition duration-500 ease-in-out transform border-2 border-white shadow-md rounded-xl focus:outline-none" do %>
              <i class="fa-solid fa-plus"></i> Create Campaign
            <% end %>
          </div>
          <div class="mt-3 rounded-lg sm:mt-0 sm:ml-3">
            <%= link_to campaigns_path, :class=>"items-center block px-10 py-3.5 text-base font-medium text-center text-gray-200 bg-gray-700 transition duration-500 ease-in-out transform border-2 border-white shadow-md rounded-xl focus:outline-none" do %>
              <i class="fa-solid fa-bars-staggered"></i> Browse Campaigns
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="flex container mx-auto px-4 justify-center items-center">
  <div class="w-full">
    <div class="w-full mx-auto my-4 bg-white">
      <div class="p-0">
        <div class="flex justify-between items-center">
          <div>
            <span class="mb-8 text-xs font-semibold tracking-widest text-black uppercase"><i class="fa-regular fa-message"></i> All Message Transactions</span>
          </div>
          <div class="text-xs text-gray-600">
            <i class="fa-solid fa-database"></i> Total <%= @all_broadcasts.count %> Broadcasts Found
          </div>
        </div>
        <div class="p-0 mt-2">
          <div class="relative overflow-x-auto">
                  <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400" id="audiences_table">
                      <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                          <tr>
                              <th scope="col" class="px-6 py-3">
                                <i class="fa-solid fa-circle-user mr-1"></i>  Name
                              </th>
                              <th scope="col" class="px-6 py-3">
                                <i class="fa-solid fa-envelope-open mr-1"></i>  Email
                              </th>
                              <th scope="col" class="px-6 py-3">
                                <i class="fa-solid fa-square-phone mr-1"></i>  Contact Number
                              </th>
                              <th scope="col" class="px-6 py-3">
                                <i class="fa-solid fa-paper-plane mr-1"></i>  Messaging
                              </th>
                              <th scope="col" class="px-6 py-3">
                                <i class="fa-solid fa-at mr-1"></i>  Mailing
                              </th>
                              <th scope="col" class="px-6 py-3">
                                <i class="fa-solid fa-calendar-day mr-1"></i>  Date
                              </th>
                          </tr>
                      </thead>
                      <tbody>
                        <% @broadcasts.each do |broadcast| %>
                          <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                            <td class="px-6 py-4">
                              <%= broadcast.receiver_name %>
                            </td>
                            <td class="px-6 py-4">
                              <%= broadcast.receiver_email %>
                            </td>
                            <td class="px-6 py-4">
                              <%= broadcast.receiver_contact_number %>
                            </td>
                            <td class="px-6 py-4">
                              <% if broadcast.message_status.present? %>
                                <div class="px-3 py-2 rounded-md bg-green-400 text-black">
                                  <i class="fa-regular fa-circle-check"></i> Delivered
                                </div>
                              <% else %>
                                <div class="px-3 py-2 rounded-md bg-yellow-400 text-black">
                                  <i class="fa-solid fa-circle-notch"></i> Pending
                                </div>
                              <% end %>
                            </td>
                            <td class="px-6 py-4">
                              <div class="px-3 py-2 rounded-md bg-green-400 text-black">
                                <i class="fa-regular fa-circle-check"></i> Delivered
                              </div>
                            </td>
                            <td class="px-6 py-4">
                              <%= broadcast.created_at.strftime("%B, %d, %Y") %>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                  </table>
              <%= paginate @broadcasts, :class=>"bg-gray-700"%>
            </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/transactions.html.erb
<% provide(:title, "All Transactions")%>

<div class="flex container mx-auto px-4 mt-3">
  <div class="w-full">
    <div class="w-full mx-auto my-4">
      <div class="flex justify-between my-3  items-center">
        <div>
          <%= link_to root_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" do %>
            <i class="fa-solid fa-arrow-left"></i> Back
          <% end %>
        </div>
        <div class="text-xs text-gray-600">
          <i class="fa-solid fa-database"></i> Total <%= @all_transactions.count %> Transactions Found
        </div>
      </div>
      <div class="p-0">
        <div class="relative overflow-x-auto">
                <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400" id="audiences_table">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th scope="col" class="px-6 py-3">
                              <i class="fa-solid fa-calendar-days mr-1"></i> Date
                            </th>
                            <th scope="col" class="px-6 py-3">
                              <i class="fa-solid fa-clock mr-1"></i> Time
                            </th>
                            <th scope="col" class="px-6 py-3">
                              <i class="fa-solid fa-swatchbook mr-1"></i>  Transaction Type
                            </th>
                            <th scope="col" class="px-6 py-3">
                              <i class="fa-solid fa-sack-dollar mr-1"></i>  Amount
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                      <% @transactions.each do |transaction| %>
                        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                          <td class="px-6 py-4">
                            <%= transaction.created_at.strftime("%B, %d, %Y") %>
                          </td>
                          <td class="px-6 py-4">
                            <%= transaction.created_at.strftime("%I:%M %p") %>
                          </td>
                          <td class="px-6 py-4">
                            <%= transaction.transaction_type %>
                          </td>
                          <td class="px-6 py-4">
                            <% if transaction.transaction_type == 'Campaign' %>
                              <div class="bg-red-400 text-black rounded-lg px-2"><i class="fa-solid fa-minus"></i> <%= transaction.amount %></div>
                            <% elsif transaction.transaction_type == 'Topup' %>
                              <div class="bg-green-400 text-black rounded-lg px-2"><i class="fa-solid fa-plus"></i> <%= transaction.amount %></div>
                            <% end %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                </table>
            </div>
        <%= paginate @transactions, :class=>"bg-gray-700"%>
      </div>
    </div>
  </div>
</div>