config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Vonage SMS Delivery Receipt
  resources :sms_delivery_receipts, only: [:create]
  
  resources :campaigns, only: [:index, :new, :create, :show]
  resources :audiences
  get 'users/profile'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: "pages#dashboard", as: :authenticated_root
      get '/users', to: 'devise/registrations#edit'
      get '/profile', to: 'users#profile', as: :profile
      get '/transactions', to: 'pages#transactions', as: :transactions
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
      get '/users', to: 'devise/registrations#new'
    end

    get '/users/password', to: 'devise/passwords#new'
  end

  root :to => "devise/sessions#new"
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :user

  validates_presence_of :title
  validates_presence_of :message
  validate :character_input

  scope :last_three_months, -> { where('created_at >= ?', DateTime.now - 3.months) }

  def character_input
    length = title.length + message.length

    if length > 145
      errors.add(:base, "Maximum 145 characters are allowed for title and message")
    end
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_campaign, only: %i[ show ]

  require "bitly"
  require 'vonage'

  def index
    @all_campaigns = current_user.campaigns.all.order(created_at: :desc)
    @campaigns = Kaminari.paginate_array(@all_campaigns).page(params[:page]).per(10)
  end

  def show
    @all_broadcasts = Broadcast.all.where(campaign_id: @campaign.id).order(created_at: :desc)
    @broadcasts = Kaminari.paginate_array(@all_broadcasts).page(params[:page]).per(10)
  end

  def new
    @campaign = current_user.campaigns.build
  end

  def create
    if current_user.wallet.balance > current_user.audiences.count
      @campaign = current_user.campaigns.build(campaign_params)
      url = params[:campaign][:url]

      if url.present? && valid_url?(url)
        begin
          client = Bitly::API::Client.new(token: '6038f593b082f2b5811a944da9e644814a131a12')
          bitlink = client.shorten(long_url: url)
          short_url = bitlink.link

          rescue Bitly::Error => e
            logger.error("Bitly API Error: #{e.message}")

            flash[:error] = "Failed to create Campaign"
              redirect_to root_path
            return url
          end

        else
        short_url = ''
      end

      @campaign.short_url = short_url
      @full_message = "#{@campaign.title} #{@campaign.message} #{@campaign.short_url}"

      respond_to do |format|
        if @campaign.save
          audiences = current_user.audiences.all

          audiences.each do |audience|
            # Send SMS
            client = Vonage::Client.new(api_key: '08b0e4dc', api_secret: 'whKYHVysVMO8Eh49')
            response = client.sms.send(
              from: '0174216717',
              to: audience.contact_number,
              text: @full_message
            )

            message_id = response["messages"][0]["message_id"]
            if response["messages"][0]["status"] == "0"
              puts "SMS sent successfully."
            else
              puts "SMS failed to send."
            end

            Broadcast.create(
              receiver_name: audience.name,
              receiver_email: audience.email,
              receiver_contact_number: audience.contact_number,
              user_id: current_user.id,
              campaign_id: @campaign.id,
              message_id: message_id
            )
            
            BroadcastWorker.perform_in(1.minute, current_user.id, audience.id, @campaign.title, @full_message)
          end

          # Update wallet
          total_charge = current_user.audiences.count
          wallet = current_user.wallet
          wallet_balance = wallet.balance
          wallet.update_attribute(:balance, wallet_balance - total_charge)

          # Add to transaction record
          Transaction.create(amount: total_charge, transaction_type: 'Campaign', user_id: current_user.id, rails_admin: "0")

          format.html { redirect_to campaign_url(@campaign), notice: "Campaign was successfully created." }
          format.json { render :show, status: :created, location: @campaign }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @campaign.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path, alert: 'Insufficient wallet balance'
    end
  end

  private
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    def campaign_params
      params.require(:campaign).permit(:title, :message, :url, :short_url, :clicks, :user_id)
    end

    def valid_url?(url)
      return false if url.include?("<script")
      url_regexp = /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?\z/ix
      url =~ url_regexp ? true : false
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_campaign.html.erb
<div id="<%= dom_id campaign %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= campaign.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Message:</strong>
    <%= campaign.message %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Url:</strong>
    <%= campaign.url %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Short url:</strong>
    <%= campaign.short_url %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Clicks:</strong>
    <%= campaign.clicks %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= campaign.user_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this campaign", campaign, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this campaign', edit_campaign_path(campaign), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/campaigns/_form.html.erb
<%= form_with(model: campaign, class: "contents") do |form| %>
  <% if campaign.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <ul>
        <% campaign.errors.each do |error| %>
          <li><i class="fa-sharp fa-regular fa-circle-dot"></i> <%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-2">
    <%= form.label :title, :class=> label_class %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-1 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :message, :class=> label_class %>
    <%= form.text_area :message, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :url, :class=> label_class %>
    <%= form.text_field :url, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.hidden_field :user_id %>
  </div>

  <div class="inline">
    <%= button_tag(type: "submit", class: "rounded-lg py-3 px-5 bg-gray-700 text-white inline-block font-medium cursor-pointer") do %>
      <i class="fa-solid fa-circle-check"></i> Create Campaign
    <% end %>
  </div>
<% end %>

app/views/campaigns/index.html.erb
<% provide(:title, "All Campaigns")%>

<div class="flex container mx-auto px-4 mt-3">
  <div class="w-full">
    <div class="w-full mx-auto my-4">
      <div class="flex justify-between my-3 items-center">
        <div>
          <%= link_to new_campaign_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" do %>
            <i class="fa-solid fa-plus"></i> Create Campaign
          <% end %>
        </div>
        <div class="text-xs text-gray-600">
          <i class="fa-solid fa-database"></i> Total <%= @all_campaigns.count %> Campaigns Found
        </div>
      </div>
      <div class="p-0">
        <div class="relative overflow-x-auto">
                <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th scope="col" class="px-6 py-3">
                              Full Message
                            </th>
                            <th scope="col" class="px-6 py-3">
                              Clicks
                            </th>
                            <th scope="col" class="px-6 py-3">
                              Created At
                            </th>
                            <th scope="col" class="px-6 py-3">
                              Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                      <% @campaigns.each do |campaign| %>
                        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                          <td class="px-6 py-4">
                            <%= campaign.title %> <%= campaign.message %> <%= campaign.short_url %>
                          </td>
                          <td class="px-6 py-4">
                            <% if campaign.clicks.present? && campaign.clicks.to_i > 0 %>
                              <div class="text-green-400"><%= campaign.clicks %></div>
                            <% else %>
                              <div class="text-yellow-400">0</div>
                            <% end %>
                          </td>
                          <td class="px-6 py-4">
                            <%= campaign.created_at.strftime("%B, %d, %Y") %>
                          </td>
                          <td class="px-6 py-4">
                            <%= link_to campaign do %>
                              <i class="fa-regular fa-circle-right text-lg"></i>
                            <% end %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                </table>
            </div>
        <%= paginate @campaigns, :class=>"bg-gray-700"%>
      </div>
    </div>
  </div>
</div>

app/views/campaigns/new.html.erb
<% provide(:title, "New Campaign")%>

<div class="flex container mx-auto px-4 mt-3">
  <div class="w-full">
    <div class="w-full mx-auto my-4 bg-white shadow-xl rounded-xl">
      <div class="p-6">
        <h1 class="font-bold text-2xl text-gray-500">Create A Campaign</h1>
        <div class="py-2 text-sm text-gray-500 font-semibold">
          You will be charged total <%= current_user.audiences.count %> credits depending on your audiences. View your <i class="fa-solid fa-arrow-right mr-2"></i> <%= link_to "Audience List", audiences_path%>
        </div>
        <%= render "form", campaign: @campaign %>
        <%= link_to campaigns_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" do %>
          <i class="fa-solid fa-angle-left"></i> Back
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/campaigns/show.html.erb
<% provide(:title, "Your Campaign")%>

<div class="flex container mx-auto px-4 mt-3">
  <div class="w-full">
    <div class="w-full mx-auto my-4">
      <div class="flex justify-between my-3">
        <div>
          <%= link_to new_campaign_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" do %>
            <i class="fa-solid fa-plus"></i> Create Campaign
          <% end %>
        </div>
        <div class="text-xs text-gray-600">
          <i class="fa-solid fa-database"></i> Total <%= @all_broadcasts.count %> Broadcasts Found
        </div>
      </div>
      <div class="p-0">
        <div class="relative overflow-x-auto">
                <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th scope="col" class="px-6 py-3">
                              Name
                            </th>
                            <th scope="col" class="px-6 py-3">
                              Email
                            </th>
                            <th scope="col" class="px-6 py-3">
                              Contact Number
                            </th>
                            <th scope="col" class="px-6 py-3">
                              Message Status
                            </th>
                            <th scope="col" class="px-6 py-3">
                              Created At
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                      <% @broadcasts.each do |broadcast| %>
                        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                          <td class="px-6 py-4">
                            <%= broadcast.receiver_name %>
                          </td>
                          <td class="px-6 py-4">
                            <%= broadcast.receiver_email %>
                          </td>
                          <td class="px-6 py-4">
                            <%= broadcast.receiver_contact_number %>
                          </td>
                          <td class="px-6 py-4">
                            <% if broadcast.message_status.present? %>
                              <div class="px-3 py-2 rounded-md bg-green-400 text-black">
                                Sent
                              </div>
                            <% else %>
                              <div class="px-3 py-2 rounded-md bg-yellow-400 text-black">
                                Pending
                              </div>
                            <% end %>
                          </td>
                          <td class="px-6 py-4">
                            <%= broadcast.created_at.strftime("%B, %d, %Y") %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                </table>
            </div>
        <%= paginate @broadcasts, :class=>"bg-gray-700"%>
      </div>
    </div>
  </div>
</div>